### ISSUE TITLE
Different input dimention compared to output dimension

### ISSUE THREAD

**Issue by titu1994** [taolei87/sru#12]
Hi, I'm trying to implement a naive version of this paper in Keras, and was wondering how is the case that - n_in != n_out handled. 

I went through the code a few times, and couldn't understand the element wise multiplication of (1 - r_t) with x_t, if x_t is of a different shape than r_t.

**Comment by taolei87** [comment]
Hi, 

When n_in != n_out, we simply add one more linear transform (say W) at the highway connection:
h'[t] = r[t] * h[t] + (1-r[t]) * (Wx[t])

Again, this multiplication can be batched together with other mm as well. that said, this (Wx) is being put into U. and I guess that's why you find the code confusing. 

We should better document the implementation. Thanks for pointing this out!

**Comment by taolei87** [comment]
Also, in speech task, the (Wx) is always included, which is discussed in the appendix.

**Comment by titu1994** [comment]
Thanks for the quick reply!

Just for further clarification, this new `W` will infact be different from equation (3) in the paper, and will not have any biases ?

**Comment by taolei87** [comment]
yes, the new W will be different to (3). and no bias term for them.

only the neural gates have biases (4) (5)

**Comment by titu1994** [comment]
Fantastic. Thank you very much for the clarification, and fantastic work on this efficient implementation in CUDA.

**Comment by taolei87** [comment]
You are very welcome!
